#!/bin/bash

# Configurations
export MDNS_SUFFIX=${MDNS_SUFFIX:-'.local'}
export WEBSOCKET_PATHS=${WEBSOCKET_PATHS:-'cable|sockjs-node|livereload|ws'}

# Sanitize the configurations
MDNS_SUFFIX=$(echo ".${MDNS_SUFFIX}" | sed 's/\.\.*/./g')
MDNS_SUFFIX=$(echo "${MDNS_SUFFIX}" | sed 's/\./\\\\./g')
export MDNS_SUFFIX="${MDNS_SUFFIX}"

# Enforce the configurations on the nginx configuration
sed -i "s/\${MDNS_SUFFIX}/${MDNS_SUFFIX}/g" \
  /etc/nginx/conf.d/default.conf
sed -i "s/\${WEBSOCKET_PATHS}/${WEBSOCKET_PATHS}/g" \
  /etc/nginx/conf.d/default.conf

# Start the supervisor
exec /usr/bin/supervisord -nc /etc/supervisor/supervisord.conf
