name: Package
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * MON'

concurrency:
  group: '${{ github.ref }}'
  cancel-in-progress: true

jobs:
  package:
    name: Build and upload the image
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Prepare the virtual environment
        uses: hausgold/actions/ci@master
        with:
          clone_token: '${{ secrets.CLONE_TOKEN }}'
          settings: '${{ github.repository }}'
          target: ci/noop
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: make build

      - name: Run the Smoke Test on the Docker image
        run: make test

      - name: Upload the Docker image
        run: make publish
